# .github/workflows/deploy-base.yml
name: Reusable Deployment

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: "Le nom de l'environnement"
      server_dir:
        required: true
        type: string
        description: "Le répertoire de déploiement sur le serveur (ex: ./rec/ ou ./prod/)"
      branch_name:
        required: true
        type: string
        description: "La branche qui déclenche le déploiement (ex: main ou develop)"
    secrets:
      ASBF_FTP_HOST:
        required: true
      ASBF_FTP_USERNAME:
        required: true
      ASBF_FTP_PASSWORD:
        required: true
      ASBF_SSH_USERNAME:
        required: true
      ASBF_SSH_HOST:
        required: true
      ASBF_SSH_PORT:
        required: true
      ASBF_SSH_PRIVATE_KEY:
        required: true
jobs:
  web-deploy:
    name: Déployer Laravel et React
    runs-on: ubuntu-latest
    environment: RECETTE
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Frontend Assets (Vite)
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.ASBF_FTP_HOST }}
          username: ${{ secrets.ASBF_FTP_USERNAME }}
          password: ${{ secrets.ASBF_FTP_PASSWORD }}
          server-dir: ${{ inputs.server_dir }}
          exclude: |
            .git/**
            .github/**
            .vscode/**
            node_modules/**
            vendor/**
            storage/logs/**
            .env.example
            *.md
            *.log
            public/hot
            resources/js/**
            docker/*
            .gitignore
            .prettierrc.json
            docker-compose.yaml
            Dockerfile
            eslint.config.js
            package.json
            package-lock.json
            tsconfig.app.json
            tsconfig.json
            tsconfig.node.json
            vite.config.js

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ASBF_SSH_PRIVATE_KEY }}

      - name: Install Deps and Migration
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.ASBF_SSH_USERNAME }}
          host: ${{ secrets.ASBF_SSH_HOST }}
          port: ${{ secrets.ASBF_SSH_PORT }}
          key: ${{ secrets.ASBF_SSH_PRIVATE_KEY }}
          script: |
            cd ./domains/asbf.bf/public_html/${{ inputs.server_dir }}
            php ../../../../composer.phar install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
