name: Déploiement sur la RECETTE

on:
  push:
    branches:
      - develop

jobs:
  call-deploy-workflow:
    name: Déploiement
    uses: ./.github/workflows/deploy-base.yml
    with:
      server_dir: "./rec/"
      branch_name: "develop"
      env: "RECETTE"
    secrets:
      ASBF_FTP_HOST: ${{ secrets.ASBF_FTP_HOST }}
      ASBF_FTP_USERNAME: ${{ secrets.ASBF_FTP_USERNAME }}
      ASBF_FTP_PASSWORD: ${{ secrets.ASBF_FTP_PASSWORD }}
      ASBF_SSH_USERNAME: ${{ secrets.ASBF_SSH_USERNAME }}
      ASBF_SSH_HOST: ${{ secrets.ASBF_SSH_HOST }}
      ASBF_SSH_PORT: ${{ secrets.ASBF_SSH_PORT }}
      ASBF_SSH_PRIVATE_KEY: ${{ secrets.ASBF_SSH_PRIVATE_KEY }}
